### ISSUE TITLE
'ref' is not defined    

### ISSUE THREAD

**Issue by Songoo7** [ballcat-projects/vue-cropper#1]
In both script or setup version of installation I end up with error 'ref' is not defined  . Have "vue": "^3.0.0".

**Comment by Songoo7** [comment]
Oh, I have to add : 
`  import { ref,onMounted } from 'vue';`

**Comment by Hccake** [comment]
Sorry, the https://github.com/antfu/unplugin-auto-import plugin was used when writing the example, so the introduction of vue-related import was ignored.

Documentation has now been fixed.
