### ISSUE TITLE
Way to get cropped data

### ISSUE THREAD

**Issue by MaikonPanazzolo** [ballcat-projects/vue-cropper#2]
Hello guys, how are you, hope you good.

I'm testing your package and it's not clear enough about how can I get the cropped data, I'm using with quasar framework and my Vue is on version 3.0.

Obs: it's not an issue.

**Comment by Hccake** [comment]
What you need should be the `getCroppedCanvas` method.

See the documentation of [cropperjs](https://github.com/fengyuanchen/cropperjs/blob/main/README.md#methods)，you can use the component's ref to call any method in the documentor.

Here is a code that uses an [example](https://github.com/ballcat-projects/vue-cropper/blob/master/example/src/App.vue).
