### ISSUE TITLE
Update package.json / ts(7016)

### ISSUE THREAD

**Issue by RedskyThirty** [ballcat-projects/vue-cropper#3]
Can you update your package.json to prevent the following error with Typescript 5+?

> Could not find a declaration file for module '@ballcat/vue-cropper'. 'c:/path-to/node_modules/@ballcat/vue-cropper/dist/index.es.js' implicitly has an 'any' type.
  There are types at 'c:/path-to/node_modules/@ballcat/vue-cropper/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@ballcat/vue-cropper' library may need to update its package.json or typings.ts(7016)

From this:

```json
{
"exports": {
    ".": {
      "import": "./dist/index.es.js",
      "require": "./dist/index.umd.js"
    }
  }
}
```

To this:

```json
{
"exports": {
    ".": {
      "import": {
		"types": "./dist/index.d.ts",
		"default": "./dist/index.es.js"
	  },
      "require": {
		"types": "./dist/index.d.ts",
		"default": "./dist/index.umd.js"
	  }
    }
  }
}
```

**Comment by Hccake** [comment]
v1.0.6 has been updated and released

**Comment by RedskyThirty** [comment]
Perfect, thanks a lot!
